# Felipe Giuste
# 5/17/2019
# Snakefile
# Randomise Whole Brain Nifti Analysis

import glob, os

#-------------------------------------------------------------------------------
# Constants
#-------------------------------------------------------------------------------
nifti_directory= "/mnt/gv0/FoxNiftis/"
randomise_directory= "/mnt/gv0/randomise/"
model_directory = "/mnt/gv0/model/"
design_matrix = "%s/group_comparison.mat" % model_directory
contrast_matrix = "%s/group_comparison.con" % model_directory
npermutations = "5000"
#ncontrasts = np.genfromtxt(contrasts, skip_header=4, comments='/').shape[0]


#-------------------------------------------------------------------------------
# Config
#-------------------------------------------------------------------------------
# SAMPLES: Folder name containing niftis for a row (128 Sources):
SAMPLES = [fname.split('/')[-1] for fname in glob.glob('%s/*'%nifti_directory)]
RANDOMISE = expand(randomise_directory+"{sample}_done", sample = SAMPLES)

#-------------------------------------------------------------------------------
# Rules
#-------------------------------------------------------------------------------
rule all:
    input: RANDOMISE
    shell:
        """
        echo "Finito";
        """

# Execute Randomise on each nifti within a RowSlice folder: Starts Container=neuroimaging_{wildcards.sample}
rule randomise:
    input: niftidir= nifti_directory+"{sample}"
    output: randomise_directory+"{sample}_done"
    shell:
        """
        docker run -t -d --rm --name neuroimaging_{wildcards.sample} fgiuste/neuroimaging
        mkdir -p {randomise_directory}/{wildcards.sample};
        for nii in `ls {input[niftidir]}`
        do
            run_randomise="randomise -i {input[niftidir]}/$nii -o {randomise_directory}/{wildcards.sample}/$nii/$nii -d {design_matrix} -t {contrast_matrix} -n {npermutations} -R -N -x --permout";
            docker exec neuroimaging_{wildcards.sample} echo $run_randomise > {randomise_directory}/{wildcards.sample}/$nii;
        done
        docker stop neuroimaging_{wildcards.sample}
        mv {randomise_directory}/{wildcards.sample} {output}
        """

# TODO: create slurm job config file to specify ntasks=1,c=1, manually override for larger jobs
## Also: slurm.conf: CR_CPU -> CR_CPU_Memory

# snakemake --jobs 256 --cluster "sbatch --ntasks=1 --cpus-per-task=1"
